export interface UnidadDetalle {
  id?: number;
  nombre?: string;
  internoId?: string;
  serie?: string;
  codigoBarra?: string;
  codigoQR?: string;
  lote?: string;
  qrGenerado?: string;
  unidadMedida?: string;
  peso?: number;
  volumen?: number;
  alto?: number;
  largo?: number;
  ancho?: number;
  color?: string;
  temperatura?: string;
  estado?: string;
  ubicacionExacta?: string;
  area?: string;
  subcategoria?: string;
  riesgo?: string;
  disponible?: boolean;
  asignadoA?: string;
  fechaIngreso?: string;
  fechaModificacion?: string;
  fechaCaducidad?: string;
  fechaInspeccion?: string;
  fechaBaja?: string;
  responsableIngreso?: string;
  modificadoPor?: string;
  proyecto?: string;
  observaciones?: string;
  imagen?: File | null;
  archivos?: File[] | null;
  imagenUrl?: string | null;
  archivosPrevios?: { id: number; nombre: string; archivoNombre: string }[] | null;
}
